# Generated by Django 5.1.6 on 2025-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
            ],
        ),
    ]
