# Generated by Django 5.1.6 on 2025-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('userid', models.CharField(default='0000', max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(default='default_username', max_length=10)),
                ('password', models.CharField(default='default_password', max_length=10)),
            ],
        ),
    ]
