# Generated by Django 5.1.6 on 2025-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='address',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='crud',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
        migrations.AddField(
            model_name='crud',
            name='userid',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='crud',
            name='username',
            field=models.CharField(default='guest', max_length=10),
        ),
    ]
