# Generated by Django 5.1.4 on 2025-02-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("penulis", models.CharField(max_length=100)),
                ("penerbit", models.CharField(max_length=100)),
                ("tahun_terbit", models.IntegerField()),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stok", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
